services:
  server:
    build: ./Server
    ports:
      - "8000:8000"
    networks:
      - TLS_1.0

  client:
    build: ./Client
    depends_on:
      - server
    networks:
      - TLS_1.0

networks:
  TLS_1.0:
